const wordList=[
    {word:"shimmer" ,
    hint:"To shine with a flickering, wavering light."},
    {word:"glisten",
    hint:"To sparkle or shine with a soft, radiant light."},
    {word:"resilient",
    hint:"Capable of recovering quickly from difficulties."},
    {word:"enigma",
    hint:"A mysterious or puzzling person, thing, or situation."},
    {word:"paradox",
    hint:"A statement or situation that appears contradictory but may reveal a truth."},
    {word:"ambivalent",
    hint:"Having mixed or conflicting feelings about something."},
    {word:"aesthetic",
    hint:"Concerned with beauty and artistic appreciation."},
    {word:"candid",
    hint:"Open, honest, and straightforward."},
    {word:"deft",
    hint:"Skillful and quick in one's movements or actions."},
    {word:"lethargic",
    hint:"Sluggish and lacking energy or enthusiasm."},
    {word:"melancholy",
    hint:"A feeling of deep sadness or sorrow."},
    {word:"amiable",
    hint:"Having a friendly and pleasant manner."},
    {word:"prolific",
    hint:"Producing many works, results, or offspring."},
    {word:"viable",
    hint:"Capable of working successfully; feasible."},
    {word:"perseverance",
    hint:" Steadfast persistence and determination in the face of difficulties."},
    {word:"cognizant",
    hint:"Fully aware or knowledgeable about something."},
    {word:"benevolent",
    hint:"Kind and generous in intention or purpose."},
    {word:"divergent",
    hint:"Tending to be different or develop in different directions."},
    {word:"nuance",
    hint:"A subtle difference or distinction in meaning or expression."},
    {word:"inherent",
    hint:" Existing as a natural and essential quality."},
    {word:"esoteric",
    hint:"Intended for or understood by a small, specific group."},
    {word:"apathy",
    hint:"Lack of interest, enthusiasm, or concern."},
    {word:"eloquent",
    hint:"Fluent and persuasive in speech or writing."},
    {word:"resonate",
    hint:" Evoke a strong feeling or connection."},
    {word:"enigma",
    hint:"A puzzling or mysterious person or situation."},
    {word:"pragmatic",
    hint:"Dealing with things in a practical and realistic way."},
    {word:"vehement",
    hint:"Showing strong and intense feeling or passion."},
    {word:"tenacious",
    hint:"Persistent and determined in pursuit of a goal."},
    {word:"pensive",
    hint:"Deeply thoughtful, often with a hint of sadness."},
    {word:"fervent",
    hint:"Displaying intense passion or enthusiasm."},
    {word:"quintessential",
    hint:"The purest and most typical example of something."},
    {word:"clandestine",
    hint:"Done secretly or in a hidden manner."},
    {word:"euphoria",
    hint:"A state of intense happiness and excitement."},
    {word:"alacrity",
    hint:"Brisk and cheerful readiness to do something."},
  
]